### ISSUE TITLE
First steps with IoT integration

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-raspberrypi-server#1]
@olagalal next steps I would like to see:

a. The app should be able to fetch, for a specific topic, a specific period of data. So please agree with @godslave05 what the API endpoint specification for that should look like. I expect the request to contain two timestamps and the topic, and the response an array of data points. This is assuming that Steve is populating data from the sensor in the database.

b. Then I would like to start testing the other direction of communication: the app will have a page with buttons for different actions that can be triggered. For this we will ask tomorrow to Steve what actuators (devices that you can control from app) he has now available for testing. You will need to provide and endpoint that allows the app to trigger an action and receive acknowledgement.
This should work in this way I think, but we will confirm tomorrow with Steve and you can document here if there are any changes

Every device that is an actuator will be subscribed to one or more topics, waiting for orders (could be more than 1 topic because maybe the device is something complex, like an AC, that can take many different kind of actions like changing temperature, switching to silent mode, changing direction of the airflow, etc).
Assuming that Steve's database has always an up-to-date database of available topics, it would be good to expand that table indicating which ones are topics created by sensors and which ones are actuators. This way it will be clear for your server and the app which topics will be populated with real time data from sensors and which topics are only for sending actions that are triggered from the app.
When the user triggers an action from the app, for example "turn on the light", the server has to publish the order to the topic that controls that device. We definitely need to discuss with Steve how will our server know exactly to which topic to publish if we will have many actuators.
The server should subscribe to exactly the same topic that is publishing too, because on that topic there should be an acknowledgement (from the hardware it self, the Arduino board will confirm that the light has indeed turned on) that allow our server to send the API response acknowledging that it is all working

**Comment by diegopau** [comment]
From Steve:

if you publish to seapod.technoid.info using topic

livingRoom/24:0A:C4:59:39:0C/RGB_LED/color

with the following messages

blue0
blue1
red0
red1
green0
green1

the RGB LED attached will switch accordingly.

**Comment by diegopau** [comment]
Steve proposed the following for confirming actions triggered from the app:
- First of all, to always use QoS level 2, for each time we publish an action. This is just acknowledge that the message is received correctly by the MQTT server
- Second, we will provide with a full confirmation that the action actually took place. In the case of the lights there will be a sensor confirming that if the order was "blue1" then the blue light is actually on. In order to do is, each topic will have a subtopic named "status", for example livingRoom/24:0A:C4:59:39:0C/RGB_LED/color/status

**Comment by diegopau** [comment]
@Bruno-N Current setup we are testing:
- Temperature readings from a tempt sensor
- Turning on /  off a simple light
- Confirmation, at the hardware level, that the light is on / off (for now this is a sensor that reads the HIGH / LOW sent to the LED.
- Steve will add a motion sensor soon.
- Steve will transition from a simple LED to a RBG LED soon, so we will be able to switch on/off specific colors individually.

We are testing 2 possible ways of interacting with the IoT setup from our apps:
- Direct communication between the app and the MQTT broker: the app reads directly sensor information by subscribing to the sensor topic. The app sends directly orders to an actuator (the light) by publishing to the MQTT server. The app get ACKs for the orders sent to the actuator by receiving a message in a /status subtopic (each actuator topic will have a subtopic for confirmations, the confirmations here are done at the hardware level, so we don't just confirm the order, but we confirm that the actual action happened)
- Communication through our web server API: 
     - Data batch requests through our web server. The app communicates with an API (located in the SeaPod) requesting data for a period of time
      - Action ordered through our web server. The app requests an action in a device (ex. turn on the light) by communicating it to our API, the request is on hold (for milliseconds) until acknowledgment is provided.

**Comment by scottdear** [comment]
@olagalal I think the acceptance criteria for this would be to create a 1 to 2 page design document.  I can help with this if you need.  I'm thinking we just consolidate the above into something that describes the approach.  Reach out when you have more time so we can talk about this further.  We can do Zoom, Discord, Slack Call, or text chat, whichever is easier.

**Comment by scottdear** [comment]
Closed as moving new direction.
