### ISSUE TITLE
Update packages to remove security vulnerabilities

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/ob-raspberrypi-server#6]
Checked out ob-raspberry pi and got 
added 1001 packages from 392 contributors and audited 1001 packages in 48.487s

w/ NodeJS/npm 12

found 215 vulnerabilities (130 low, 4 moderate, 81 high)

  run `npm audit fix` to fix them, or `npm audit` for details
  
  I ran audit fix (will check in to tree).
  
  And got:
  
  pi@raspberrypi:~/git/ob-raspberrypi-server $ npm audit fix

npm WARN ob-raspberrypi-server@1.0.0 No repository field.

updated 1 package in 16.866s

fixed 115 of 215 vulnerabilities in 1001 scanned packages

  100 vulnerabilities required manual review and could not be updated

Acceptance Criteria:

Can run npm install w/out showing vulnerabilities.
Pull request w/ updated package-lock.json

This is the manual review part to either remove or update the dependencies and regression test for any breaking changes.

This is the second half of #5

**Comment by scottdear** [comment]
I ran yarn install and it came back w/ 
arning update > base-config-process > base-option > set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.

warning update > data-store > union-value > set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.

warning update > common-config > question-cache > set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.

warning update > gulp-choose-files > question-cache > set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.

warning update > data-store > cache-base > set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.

warning update > assemble-core > templates > set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.

warning update > base-config-process > base-option > option-cache > set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.

warning update > base-config-process > base-config-schema > map-schema > set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.

warning update > base-cli-process > base-cli > base-argv > expand-args > set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.

warning update > assemble-core > templates > engine-base > engine > set-value@0.2.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.

warning update > base-cli-process > base-cli > base-argv > expand-args > expand-object > set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.

which may provide some clues as to what needs to be upgraded.  It would be good if both npm and yarn report no errors.

**Comment by olagalal** [comment]
Did you update those packages in this PR https://github.com/oceanbuilders/ob-raspberrypi-server/issues/5?

**Comment by scottdear** [comment]
@olagalal yes I did.  I created a development branch and merged the feature branch into the development branch.  When we get ready to do a release we'll do a pull request from the development branch to the master branch.  In that way, we can fix bugs in production without interrupting forward progress of the development team :)
